language: python
sudo: false
install:
    - python3 setup.py install
    - pip3 install tox

matrix:
    include:
        - python: 3.5
          env: TOXENV=py35
        - python: 3.5
          env: TOXENV=pep8

services:
    - postgresql

before_script:
  - psql -c 'create database test;' -U postgres

script: tox
