language: python
sudo: false
install:
    - python setup.py install
    - pip install tox

matrix:
    include:
        - python: 3.5
          env: TOXENV=py35
        - python: 3.5
          env: TOXENV=pep8
        - python: 3.4
          env: TOXENV=py34

services:
    - postgresql

before_script:
  - psql -c 'create database test;' -U postgres
  - python3 efesto/scripts/travis.py
  - python3 efesto/scripts/quickstart.py --no-admin

script: tox
